packages:
  - "backend"
  - "frontend"

allowBuilds:
  esbuild: true
  mongodb-memory-server: true
  msgpackr-extract: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  tesseract.js: true
